import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, it, expect } from 'vitest'
import { parseFlexStatements } from './flexStatementParser'
import { isInstrumentSummary } from './fifoSummary'
import type { FifoSummaryRow } from './flexReadRepository'
import type { FlexPerformanceSummary, FlexStatement } from '@shared/domain/flex'

/**
 * The committed demo exports (`demo/flex/`, generated by `npm run demo:generate`) held against
 * the parser.
 *
 * Unlike the real exports these are **not** gitignored, so this suite always runs — which is
 * the point. The demo is what gets shown to other people, and a generator that drifts out of
 * the parser's contract would only be discovered while presenting. Every assertion below is an
 * identity the app's views are read against, not a snapshot of the figures: retuning the
 * fictional portfolio is expected and must not touch this file.
 */

const DEMO_DIR = join(process.cwd(), 'demo', 'flex')

function parseDemo(year: number): FlexStatement {
  const [statement] = parseFlexStatements(readFileSync(join(DEMO_DIR, `demo-${year}.xml`), 'utf8'))
  if (!statement) throw new Error(`demo-${year}.xml carried no statement`)
  return statement
}

const YEARS = [2024, 2025, 2026] as const

/** The years whose export ends between a declaration and its payment (see `universe.mjs`). */
const YEARS_WITH_ACCRUALS = [2025, 2026] as const

/**
 * The real predicate, applied to the parsed shape. `isInstrumentSummary` reads only `symbol`,
 * but it takes the *stored* row — asserting against a re-implementation here would leave the
 * demo export free to drift away from the one rule that drops IBKR's aggregate line.
 */
const isInstrument = (row: FlexPerformanceSummary): boolean =>
  isInstrumentSummary(row as unknown as FifoSummaryRow)

describe('demo Flex exports', () => {
  it.each(YEARS)('demo-%i.xml parses into one statement', (year) => {
    const statement = parseDemo(year)
    expect(statement.accountId).toMatch(/^U\d+$/)
    expect(statement.baseCurrency).toBe('EUR')
    expect(statement.navChange).not.toBeNull()
  })

  it.each(YEARS)('demo-%i.xml carries every section the views read', (year) => {
    const s = parseDemo(year)
    expect(s.equitySummaries.length).toBeGreaterThan(40)
    expect(s.openPositions.length).toBeGreaterThan(0)
    expect(s.priorPeriodPositions.length).toBeGreaterThan(0)
    expect(s.trades.length).toBeGreaterThan(0)
    expect(s.cashTransactions.length).toBeGreaterThan(0)
    expect(s.securities.length).toBeGreaterThan(0)
  })

  it.each(YEARS_WITH_ACCRUALS)('demo-%i.xml ends between a declaration and its payment', (year) => {
    // Generated to straddle one, so the Dividends view's upcoming-payments panel has something
    // in it whichever of the two full statements is the latest imported (DDR-0010). The opening
    // quarter is excluded: nothing was declared and unpaid when it closed.
    expect(parseDemo(year).openDividendAccruals.length).toBeGreaterThan(0)
  })

  it.each(YEARS)('demo-%i.xml closes its daily NAV series on the reported ending value', (year) => {
    const s = parseDemo(year)
    const last = s.equitySummaries[s.equitySummaries.length - 1]
    expect(last).toBeDefined()
    // The identity DDR-0050 relies on when it swaps the reconstructed curve for IBKR's own:
    // the series' last point *is* the headline ending value.
    expect(last?.total).toBeCloseTo(s.navChange?.endingValue ?? 0, 4)
  })

  it.each(YEARS)('demo-%i.xml reconciles ChangeInNAV to its own components', (year) => {
    const nav = parseDemo(year).navChange
    if (!nav) throw new Error('demo statement carried no ChangeInNAV')
    // `fxTranslation` is absent from the parsed shape (nothing reads it), so this asserts only
    // that the components the app *does* read account for nearly all of the change.
    const explained =
      nav.mtm + nav.depositsWithdrawals + nav.dividends + nav.withholdingTax + nav.commissions
    expect(Math.abs(nav.endingValue - nav.startingValue - explained)).toBeLessThan(
      Math.abs(nav.endingValue) * 0.05,
    )
  })

  it.each(YEARS)('demo-%i.xml carries the "Total (All Assets)" aggregate row', (year) => {
    const summaries = parseDemo(year).performanceSummaries
    const aggregate = summaries.filter((row) => !isInstrument(row))
    // Generated on purpose: it is the row Bug #103's sibling trap depends on, and a demo export
    // without it stops exercising `isInstrumentSummary` at all.
    expect(aggregate).toHaveLength(1)

    const instruments = summaries.filter(isInstrument)
    expect(instruments.length).toBeGreaterThan(0)
    const summed = instruments.reduce((total, row) => total + row.totalFifoPnl, 0)
    expect(aggregate[0]?.totalFifoPnl).toBeCloseTo(summed, 4)
  })

  it('covers every opening purchase, so a dividend divides by the shares really held', () => {
    // The Dividends view reconstructs share counts from imported trades. A position opened
    // before the earliest statement is invisible to it, and the per-share figure it prints is
    // then a payment divided by the wrong number — which is why the demo imports the quarter
    // the account opened in rather than starting at the first full year.
    const held = new Set(parseDemo(2026).openPositions.map((p) => p.conid))
    const opened = new Set(
      YEARS.flatMap(parseDemo)
        .flatMap((s) => s.trades)
        .filter((t) => t.quantity > 0)
        .map((t) => t.conid),
    )
    for (const conid of held) expect(opened).toContain(conid)
  })

  it("every open position's percentOfNAV agrees with the statement's ending NAV", () => {
    const s = parseDemo(2026)
    const nav = s.navChange?.endingValue ?? 0
    for (const position of s.openPositions) {
      const share = ((position.markPrice ?? 0) * position.position * position.fxRateToBase * 100) / nav
      expect(position.percentOfNav ?? 0).toBeCloseTo(share, 1)
    }
  })

  it('names an issuer country for every position the Allocation map has to place', () => {
    const s = parseDemo(2026)
    const countries = new Map(s.securities.map((sec) => [sec.conid, sec.issuerCountryCode]))
    for (const position of s.openPositions) {
      expect(countries.get(position.conid)).toMatch(/^[A-Z]{2}$/)
    }
  })

  it('holds the statements to non-overlapping periods', () => {
    // Realized P&L is summed across statements and unrealized is not (Bug #103); overlapping
    // demo periods would double the first half of that and hide the bug the app guards against.
    const statements = YEARS.map(parseDemo)
    for (let i = 1; i < statements.length; i += 1) {
      expect(statements[i - 1]?.toDate).toBeLessThan(statements[i]?.fromDate ?? 0)
    }
  })
})
